# Site settings
title: Vegan Academics
email: mendelkranz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Two wannabee academics who are mostly/almost vegan.
  Writing about religious studies and being vegan in the academy. 
baseurl: "/mendelkranz.github.io" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: mendelkranz
github_username:  mendelkranz

# Build settings
markdown: kramdown
